name: Checkout and Set Image Tag

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set image tag
      shell: bash
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        # remove refs/heads and replace slashes (/) with dashes (-)
        BRANCH_NAME="${GITHUB_REF#refs/heads/}" && BRANCH_NAME="${BRANCH_NAME//\//-}"

        if [ "$BRANCH_NAME" == "main" ]; then
          TAG="${REPO_NAME}-${GITHUB_RUN_NUMBER}"
        else
          TAG="${REPO_NAME}-${BRANCH_NAME}-${GITHUB_RUN_NUMBER}"
        fi

        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
