name: Checkout and Set Image Tag

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set image tag
      shell: bash
      run: |
        IMAGE_TAG="${GITHUB_REF_NAME}-${GITHUB_RUN_NUMBER}"
        echo "IMAGE_TAG" >> $GITHUB_ENV
