name: Test Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: false
        type: string
        default: "16"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        run: |
          echo "Deploy to ${{ inputs.node-version }}"
          echo "DEV_VAR= ${{ vars.DEV_VAR }}"
          echo "DEV_SECRET= ${{ secrets.DEV_SECRET }}"
          echo "PROD_VAR= ${{ vars.PROD_VAR }}"
          echo "PROD_SECRET= ${{ secrets.PROD_SECRET }}"

      - name: Trigger AWS build
        run: |
          echo "Trigger aws build"
