name: Test Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: true
        type: string
        default: "16"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        run: echo "Deploy to ${{ inputs.node-version }}"
