name: Deployment
run-name: Manual Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  common-workflow:
    uses: ./.github/workflows/common.yml
    with:
      node-version: "18"

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deployment
        run: echo "Deploy to ${{ inputs.environment }}"
